import Head from 'next/head'

import { Header, Banner, SmallCard, MediumCard, LargeCard, Footer } from '../components'

export default function Home({exploreData, cardsData}) {
  return (
    <div>
      <Head>
        <title>Airbnb app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Header />
      <Banner />

      <main className='relative px-10 sm:px-20 bg-white z-30'>
        <div className='max-w-7xl mx-auto'>
          <section className='pt-6'>
            <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>
            {/* Pull some data from a server -API endpoint */}
            <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
              {
                exploreData?.map((item) => (
                  <SmallCard key={item.location} item={item}/>
                ))
              }
            </div>
          </section>

          <section>
            <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>
            
            <MediumCard cardsData={cardsData}/>
          </section>

          <LargeCard 
            img='https://links.papareact.com/4cj'
            title='The Greatest Qutdoors'
            description='Wishlists curated by Airbnb'
            buttionT
            ext ='Get Inspired'
          />
        </div>
      </main>
      <Footer />
    </div>
  )
}

export async function getStaticProps() {

    const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
      (res) => res.json()
    );

    const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT").then(
      (res) => res.json()
    )

    return{
      props: {
        exploreData,
        cardsData
      }
    }
}